# open3d

## 基础
colab不支持open3d三维可视化，jupyter notebook本地运行可视化是弹窗显示

In [24]:
import open3d as o3d
import numpy as np
# 读取 展示
datadir = "PointCloudData/rectangle.ply"
pcd = o3d.io.read_point_cloud(datadir)
print(pcd)
print(np.asarray(pcd.points))
print(np.asarray(pcd.points).shape)
# o3d.visualization.draw_geometries([pcd],mesh_show_wireframe=True)

PointCloud with 43381 points.
[[-0.01911783 -0.03290318  0.98277861]
 [-0.01802992 -0.03287225  0.98180258]
 [-0.01769577 -0.03290823  0.98286402]
 ...
 [ 0.02130458  0.07828158  0.98029351]
 [ 0.0216579   0.07827332  0.98019391]
 [ 0.02201807  0.0782923   0.98043334]]
(43381, 3)


In [7]:
# import numpy as np
# import open3d as o3d
# # 从np生成
# if __name__ =="__main__":
#     points = np.random.rand(10000, 3)
#     pcd = o3d.geometry.PointCloud()
#     pcd.points = o3d.utility.Vector3dVector(points)
#     o3d.visualization.draw_geometries([pcd])

In [31]:
# 下采样
downpcd = pcd.voxel_down_sample(voxel_size = 0.001)
# 法线估计，按“N”查看法线
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
# np.asarray(downpcd.normals).shape
o3d.visualization.draw_geometries([downpcd])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 


In [32]:
# 裁剪
pcd.point_cloud_path

AttributeError: 'open3d.cpu.pybind.geometry.PointCloud' object has no attribute 'point_cloud_path'