# open3d
官方文档地址：http://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html

## 基础
colab不支持open3d三维可视化，jupyter notebook本地运行可视化是弹窗显示

In [1]:
import open3d as o3d
import numpy as np
# 读取 展示
datadir = "PointCloudData\\yk_examples\\rectangle.ply"
pcd = o3d.io.read_point_cloud(datadir)
print(pcd)
print(np.asarray(pcd.points))
print(np.asarray(pcd.points).shape)

# 弹窗"Ctrl+C"可以复制参数，粘贴即可得到缩放、视角之类的东西
o3d.visualization.draw_geometries([pcd],mesh_show_wireframe=True)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
PointCloud with 43381 points.
[[-0.01911783 -0.03290318  0.98277861]
 [-0.01802992 -0.03287225  0.98180258]
 [-0.01769577 -0.03290823  0.98286402]
 ...
 [ 0.02130458  0.07828158  0.98029351]
 [ 0.0216579   0.07827332  0.98019391]
 [ 0.02201807  0.0782923   0.98043334]]
(43381, 3)


In [17]:
# 下采样
downpcd = pcd.voxel_down_sample(voxel_size = 0.001)
# 法线估计，按“N”查看法线，不计算也能直接显示法线
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
# np.asarray(downpcd.normals).shape
o3d.visualization.draw_geometries([downpcd])

In [2]:
# 裁剪
pcd = o3d.io.read_point_cloud("PointCloudData\\isl-org_examples\\fragment.ply")
vol = o3d.visualization.read_selection_polygon_volume("PointCloudData\\isl-org_examples\\cropped.json")
chair = vol.crop_point_cloud(pcd)
o3d.visualization.draw_geometries([chair],
                                  zoom=0.7,
                                  front=[0.5439, -0.2333, -0.8060],
                                  lookat=[2.4615, 2.1331, 1.338],
                                  up=[-0.1781, -0.9708, 0.1608])


In [21]:
# 绘制
chair.paint_uniform_color([1,1,0])
o3d.visualization.draw_geometries([chair],
                                zoom=0.7,
                                front=[0.5439, -0.2333, -0.8060],
                                lookat=[2.4615, 2.1331, 1.338],
                                up=[-0.1781, -0.9708, 0.1608]
                                )

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 


In [5]:
# 为【源点云(pcd)中的每个点】计算与【目标点云(chair)中最近的点】的距离
# 可计算两个点云之间的差异(倒角距离)
dists = pcd.compute_point_cloud_distance(chair)
dists = np.asarray(dists)
ind = np.where(dists > 0.01)[0]
pcd_without_chair = pcd.select_by_index(ind)
o3d.visualization.draw_geometries([pcd_without_chair],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

In [18]:
# 包围多边体

(31337,)

In [19]:
np.asarray(pcd.compute_point_cloud_distance(chair)).shape

(196133,)