# open3d

## 基础

In [2]:
import open3d as o3d
import numpy as np
# 读取 展示
if __name__ =="__main__":
    datadir = "J:\Document\Coding\PointCloud\model_1.ply"
    pcd = o3d.io.read_point_cloud(datadir)
    print(pcd)
    print(np.asarray(pcd.points))
    o3d.visualization.draw_geometries([pcd],mesh_show_wireframe=True)

PointCloud with 2426 points.
[[ 3.61914677e-03 -6.53125495e-02  1.17495155e+00]
 [ 3.61852837e-03 -6.46385327e-02  1.17494941e+00]
 [ 2.94297212e-03 -6.39582351e-02  1.17483580e+00]
 ...
 [ 8.67882685e-04  1.15810130e-02  1.18325245e+00]
 [ 4.14819340e-04  1.24894679e-02  1.18369329e+00]
 [-4.93057072e-04  1.36156855e-02  1.18302321e+00]]


In [12]:
import numpy as np
import open3d as o3d
# 从np生成
if __name__ =="__main__":
    points = np.random.rand(10000, 3)
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points)
    o3d.visualization.draw_geometries([pcd])

In [2]:
# 下采样
downpcd = pcd.voxel_down_sample(voxel_size = 0.05)
# 法线估计，按“N”查看法线
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
o3d.visualization.draw_geometries([downpcd])

In [14]:
asfa